In [4]:
## importing necessary library
import numpy as np
from sklearn.linear_model import LogisticRegression

In [6]:
## Create variables
#x represents the size of a tumor in centimeters.
x = np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)

#y represents whether or not the tumor is cancerous (0 for "No", 1 for "Yes").
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [9]:
logreg= LogisticRegression()
logreg.fit(x,y)

LogisticRegression()

In [12]:
## predicting a random value
predict= logreg.predict(np.array([3.45]).reshape(-1,1))
predict

array([0])

In [13]:
## Finding the odds
log_odd= logreg.coef_
odds= np.exp(log_odd)
odds

array([[4.03541657]])

In [ ]:
## This tells us that as the size of a tumor increases by 1mm the odds of it being a cancerous tumor increases by 4x.

# creating function for finding the probability

In [14]:
def probabilty(model,value):
    log_odds= model.coef_ *value + model.intercept_
    odds=np.exp(log_odds)
    prb= odds/(1+odds)
    return(prb)

In [16]:
print(probabilty(logreg,x))

[[0.60749955]
 [0.19268876]
 [0.12775886]
 [0.00955221]
 [0.08038616]
 [0.07345637]
 [0.88362743]
 [0.77901378]
 [0.88924409]
 [0.81293497]
 [0.57719129]
 [0.96664243]]


In [ ]:
## Results explained
3.78 0.61 The probability that a tumor with the size 3.78cm is cancerous is 61%.

2.44 0.19 The probability that a tumor with the size 2.44cm is cancerous is 19%.

2.09 0.13 The probability that a tumor with the size 2.09cm is cancerous is 13%.