In [3]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv(r'C:\Users\User\Documents\python code\carprices.csv')

In [10]:
df

Car Model  Mileage  Sell Price  Age
0           BMW X5    69000       18000    6
1           BMW X5    35000       34000    3
2           BMW X5    57000       26100    5
3           BMW X5    22500       40000    2
4           BMW X5    46000       31500    4
5             Audi    59000       29400    5
6             Audi    52000       32000    5
7             Audi    72000       19300    6
8             Audi    91000       12000    8
9   Mercedez Benz     67000       22000    6
10  Mercedez Benz     83000       20000    7
11  Mercedez Benz     79000       21000    7
12  Mercedez Benz     59000       33000    5
13          Toyota    51000       42000    4
14          Toyota    65000       32000    7
15          Toyota    39000       55000    5

In [11]:
df.isnull().sum()

Car Model     0
Mileage       0
Sell Price    0
Age           0
dtype: int64

In [12]:
df.Age

0     6
1     3
2     5
3     2
4     4
5     5
6     5
7     6
8     8
9     6
10    7
11    7
12    5
13    4
14    7
15    5
Name: Age, dtype: int64

In [14]:
df.Age.mean()

5.3125

In [18]:
from sklearn import linear_model

In [19]:
reg= linear_model.LinearRegression()

In [20]:
df

Car Model  Mileage  Sell Price  Age
0           BMW X5    69000       18000    6
1           BMW X5    35000       34000    3
2           BMW X5    57000       26100    5
3           BMW X5    22500       40000    2
4           BMW X5    46000       31500    4
5             Audi    59000       29400    5
6             Audi    52000       32000    5
7             Audi    72000       19300    6
8             Audi    91000       12000    8
9   Mercedez Benz     67000       22000    6
10  Mercedez Benz     83000       20000    7
11  Mercedez Benz     79000       21000    7
12  Mercedez Benz     59000       33000    5
13          Toyota    51000       42000    4
14          Toyota    65000       32000    7
15          Toyota    39000       55000    5

In [40]:
x1=df[['Age']]
x1
x2=df[['Mileage']]
x2

Mileage
0     69000
1     35000
2     57000
3     22500
4     46000
5     59000
6     52000
7     72000
8     91000
9     67000
10    83000
11    79000
12    59000
13    51000
14    65000
15    39000

In [41]:
y=df['Sell Price']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
13    42000
14    32000
15    55000
Name: Sell Price, dtype: int64

In [44]:
reg.fit(x1,y)

LinearRegression()

In [45]:
reg.coef_

array([-4440.23372287])

In [47]:
reg.intercept_

52794.9916527546

In [48]:
reg.fit(x1,x2,y)

LinearRegression()

In [49]:
reg.coef_

array([[10312.34703348]])

In [50]:
reg.intercept_

array([2930.47414157])

In [52]:
#lets run the multiple regression
xnew=df[['Age','Mileage']]
xnew
ynew=df['Sell Price']
ynew

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
13    42000
14    32000
15    55000
Name: Sell Price, dtype: int64

In [53]:
reg.fit(xnew,ynew)

LinearRegression()

In [54]:
reg.coef_

array([ 6.42785653e+03, -1.00532562e+00])

In [55]:
reg.intercept_

54529.555975698604

In [57]:
reg.predict([[10,90000]])

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([28328.81534333])